# Generated by Django 3.0.3 on 2020-02-08 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Базовая ссылка')),
                ('icon', models.CharField(max_length=255, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephone', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'ordering': ('user', '-add_date'),
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Ник в соц сети')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_card_app.Social', verbose_name='Социальная сеть')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Социальная сеть работника',
                'verbose_name_plural': 'Социальные сети работников',
                'ordering': ('user', '-add_date'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('work_email', models.EmailField(max_length=254, verbose_name='Рабочая почта')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('company_name', models.TextField(blank=True, verbose_name='Название компании')),
                ('field_of_activity', models.CharField(blank=True, max_length=255, verbose_name='Сфеера деятельности')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткая информация о компании')),
                ('site', models.URLField(blank=True, verbose_name='Сайт')),
                ('registration', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_card', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Визитка',
                'verbose_name_plural': 'Визитки',
                'ordering': ('user', '-registration'),
            },
        ),
    ]
